name: Terraform Apply
description: Download a plan artifact and apply using terraform-plan-apply.
author: Tesco Terraform Tooling Team
inputs:
  working_directory:
    description: Directory containing Terraform configuration.
    required: false
    default: "."
  backend_config_file:
    description: Optional backend configuration file passed to terraform init.
    required: false
    default: ""
  var_file:
    description: Optional tfvars file passed to terraform apply (used when no plan file is provided).
    required: false
    default: ""
  plan_file:
    description: Plan file name to apply (downloaded via artifact).
    required: false
    default: "terraform.tfplan"
  artifact_name:
    description: Name of the plan artifact to download.
    required: false
    default: "tfplan"
  additional_init_args:
    description: Extra arguments appended to terraform init.
    required: false
    default: ""
  additional_apply_args:
    description: Additional arguments appended to terraform apply.
    required: false
    default: ""
  apply_auto_approve:
    description: Use -auto-approve when running terraform apply.
    required: false
    default: "false"
  aws_role_to_assume:
    description: Optional IAM role ARN to assume before running Terraform.
    required: false
    default: ""
  aws_region:
    description: AWS region used when assuming the role.
    required: false
    default: "eu-west-1"
  aws_session_name:
    description: Session name for STS assume-role calls.
    required: false
    default: "github-actions"
runs:
  using: composite
  steps:
    - name: Download plan artifact
      uses: actions/download-artifact@v4
      with:
        name: ${{ inputs.artifact_name }}
        path: ${{ inputs.working_directory }}

    - name: Terraform apply
      uses: ./.github/actions/terraform-plan-apply
      with:
        working_directory: ${{ inputs.working_directory }}
        backend_config_file: ${{ inputs.backend_config_file }}
        additional_init_args: ${{ inputs.additional_init_args }}
        run_plan: false
        plan_file: ${{ inputs.plan_file }}
        var_file: ${{ inputs.var_file }}
        additional_apply_args: ${{ inputs.additional_apply_args }}
        apply_auto_approve: ${{ inputs.apply_auto_approve }}
        run_apply: true
        aws_role_to_assume: ${{ inputs.aws_role_to_assume }}
        aws_region: ${{ inputs.aws_region }}
        aws_session_name: ${{ inputs.aws_session_name }}

