name: Terraform Apply
description: Download plan artifact, compute backend path from environment, and run terraform apply. Assumes AWS credentials configured by the caller.
author: Tesco Terraform Tooling Team
inputs:
  working_directory:
    description: Directory containing Terraform configuration.
    required: false
    default: "."
  environment:
    description: Environment name (sandbox/dev/prod) used to derive backend path and role
    required: true
runs:
  using: composite
  steps:
    - name: Download plan artifact
      uses: actions/download-artifact@v4
      with:
        name: tfplan
        path: ${{ inputs.working_directory }}

    - name: Terraform apply
      shell: bash
      working-directory: ${{ inputs.working_directory }}
      run: |
        set -euo pipefail
        ENV_NAME="${{ inputs.environment }}"
        PLAN_FILE="plan-${ENV_NAME}.tfplan"
        terraform init -input=false -reconfigure -backend-config="env/${ENV_NAME}/${ENV_NAME}.tfbackend"
        APPLY_ARGS=("-input=false" "$PLAN_FILE")
        echo "Running: terraform apply ${APPLY_ARGS[*]}"
        terraform apply "${APPLY_ARGS[@]}"
