name: Terraform Apply
description: Download plan artifact, compute standard backend path from environment, assume role via env-scoped vars, and run terraform apply.
author: Tesco Terraform Tooling Team
inputs:
  working_directory:
    description: Directory containing Terraform configuration.
    required: false
    default: "."
  environment:
    description: Environment name (sandbox/dev/prod) used to derive backend path and role
    required: true
runs:
  using: composite
  steps:
    - name: Download plan artifact
      uses: actions/download-artifact@v4
      with:
        name: tfplan
        path: ${{ inputs.working_directory }}

    - name: Configure AWS credentials
      uses: aws-actions/configure-aws-credentials@v4
      with:
        role-to-assume: arn:aws:iam::${{ vars.AWS_ACCOUNT_ID }}:role/ims-terraform-infrastructure-role-${{ inputs.environment }}
        aws-region: eu-west-1
        role-session-name: github-actions

    - name: Terraform apply
      shell: bash
      working-directory: ${{ inputs.working_directory }}
      run: |
        set -euo pipefail
        ENV_NAME="${{ inputs.environment }}"
        BACKEND_CONFIG_FILE="env/${ENV_NAME}/${ENV_NAME}.tfbackend"
        PLAN_FILE="plan-${ENV_NAME}.tfplan"
        terraform init -input=false -reconfigure -backend-config="$BACKEND_CONFIG_FILE"
        APPLY_ARGS=("-input=false" "$PLAN_FILE")
        echo "Running: terraform apply ${APPLY_ARGS[*]}"
        terraform apply "${APPLY_ARGS[@]}"
