name: Terraform Plan and Apply
description: Delegate to individual plan/apply composites; compute standard backend/plan paths from environment.
author: Tesco Terraform Tooling Team

inputs:
  environment:
    description: Environment name (sandbox/dev/prod) used to derive backend/plan paths
    required: true
  action_type:
    description: Which action to perform: plan, apply, or plan_apply
    required: false
    default: "plan"

outputs:
  plan_status:
    description: Result of terraform plan (changes, no_changes, or empty when skipped).
    value: ${{ steps.plan_wrap.outputs.plan_status }}
  plan_exit_code:
    description: Exit code returned by terraform plan (useful with -detailed-exitcode).
    value: ${{ steps.plan_wrap.outputs.plan_exit_code }}
  plan_file:
    description: Path to the generated plan file.
    value: ${{ steps.plan_wrap.outputs.plan_file }}
  plan_text_path:
    description: Path to the rendered human-readable plan file.
    value: ${{ steps.plan_wrap.outputs.plan_text_path }}
  plan_json_path:
    description: Path to the rendered JSON plan file.
    value: ${{ steps.plan_wrap.outputs.plan_json_path }}

runs:
  using: composite
  steps:
    - name: Terraform plan (composite)
      id: plan_wrap
      if: ${{ inputs.action_type != 'apply' }}
      uses: ./.github/actions/terraform-plan
      with:
        environment: ${{ inputs.environment }}

    - name: Terraform apply (composite)
      if: ${{ inputs.action_type != 'plan' }}
      uses: ./.github/actions/terraform-apply
      with:
        environment: ${{ inputs.environment }}
