name: Terraform Plan
description: Compute standard backend/plan paths from environment, optionally assume AWS role, and run terraform plan with artifacts.
author: Tesco Terraform Tooling Team
inputs:
  working_directory:
    description: Directory containing Terraform configuration.
    required: false
    default: "."
  environment:
    description: Environment name (sandbox/dev/prod) used to derive backend/plan paths and role
    required: true
  var_file:
    description: Optional path to a tfvars file relative to working_directory.
    required: false
    default: ""
  aws_role_to_assume:
    description: Optional full AWS role ARN to assume.
    required: false
    default: ""
  aws_account_id:
    description: Optional AWS account ID (used to compute a standard role ARN when aws_role_to_assume is empty).
    required: false
    default: ""
  aws_region:
    description: AWS region for credentials configuration.
    required: false
    default: "eu-west-1"
  
outputs:
  plan_status:
    description: Result of terraform plan (changes, no_changes).
    value: ${{ steps.plan.outputs.plan_status }}
  plan_exit_code:
    description: Exit code returned by terraform plan (useful with -detailed-exitcode).
    value: ${{ steps.plan.outputs.plan_exit_code }}
  plan_file:
    description: Path to the generated plan file.
    value: ${{ steps.plan.outputs.plan_file }}
  plan_text_path:
    description: Path to the rendered human-readable plan file.
    value: ${{ steps.capture.outputs.plan_text_path }}
  plan_json_path:
    description: Path to the rendered JSON plan file (empty when disabled).
    value: ${{ steps.capture.outputs.plan_json_path }}
runs:
  using: composite
  steps:
    - name: Compute role ARN
      id: role
      shell: bash
      env:
        IN_ROLE: ${{ inputs.aws_role_to_assume }}
        IN_ACCT: ${{ inputs.aws_account_id }}
        ENV_NAME: ${{ inputs.environment }}
      run: |
        set -euo pipefail
        ROLE_ARN="${IN_ROLE}"
        if [ -z "$ROLE_ARN" ] && [ -n "${IN_ACCT}" ]; then
          ROLE_ARN="arn:aws:iam::${IN_ACCT}:role/ims-terraform-infrastructure-role-${ENV_NAME}"
        fi
        echo "role_arn=$ROLE_ARN" >> "$GITHUB_OUTPUT"

    - name: Configure AWS credentials
      if: ${{ steps.role.outputs.role_arn != '' }}
      uses: aws-actions/configure-aws-credentials@v4
      with:
        role-to-assume: ${{ steps.role.outputs.role_arn }}
        aws-region: ${{ inputs.aws_region }}
        role-session-name: github-actions

    - name: Terraform init
      shell: bash
      working-directory: ${{ inputs.working_directory }}
      run: |
        set -euo pipefail
        ENV_NAME="${{ inputs.environment }}"
        terraform init -input=false -reconfigure -backend-config="env/${ENV_NAME}/${ENV_NAME}.tfbackend"

    - name: Terraform plan
      id: plan
      shell: bash
      working-directory: ${{ inputs.working_directory }}
      run: |
        set -euo pipefail
        ENV_NAME="${{ inputs.environment }}"
        PLAN_FILE="plan-${ENV_NAME}.tfplan"
        PLAN_ARGS=("-input=false" "-no-color" "-detailed-exitcode" "-out=$PLAN_FILE")
        if [ -n "${{ inputs.var_file }}" ]; then
          if [ -f "${{ inputs.var_file }}" ]; then
            PLAN_ARGS+=("-var-file=${{ inputs.var_file }}")
          else
            echo "Warning: var_file path '${{ inputs.var_file }}' not found; continuing without it" >&2
          fi
        fi
        set +e
        terraform plan "${PLAN_ARGS[@]}"
        EXIT_CODE=$?
        set -e
        case $EXIT_CODE in
          0) PLAN_STATUS="no_changes" ;;
          2) PLAN_STATUS="changes" ;;
          *) echo "terraform plan failed with exit code $EXIT_CODE" >&2; exit "$EXIT_CODE" ;;
        esac
        echo "plan_status=$PLAN_STATUS" >> "$GITHUB_OUTPUT"
        echo "plan_exit_code=$EXIT_CODE" >> "$GITHUB_OUTPUT"
        echo "plan_file=$(pwd)/$PLAN_FILE" >> "$GITHUB_OUTPUT"

    - name: Capture plan outputs
      id: capture
      if: ${{ success() }}
      shell: bash
      working-directory: ${{ inputs.working_directory }}
      run: |
        set -euo pipefail
        ENV_NAME="${{ inputs.environment }}"
        PLAN_FILE="plan-${ENV_NAME}.tfplan"
        terraform show -no-color "$PLAN_FILE" > plan.txt
        terraform show -json "$PLAN_FILE" > plan.json
        echo "plan_text_path=$(pwd)/plan.txt" >> "$GITHUB_OUTPUT"
        echo "plan_json_path=$(pwd)/plan.json" >> "$GITHUB_OUTPUT"

    - name: Upload plan artifact
      if: ${{ steps.plan.outputs.plan_file != '' }}
      uses: actions/upload-artifact@v4
      with:
        name: tfplan
        path: |
          ${{ steps.plan.outputs.plan_file }}
          ${{ steps.capture.outputs.plan_text_path }}
          ${{ steps.capture.outputs.plan_json_path }}
        if-no-files-found: ignore
