name: Terraform Setup
description: >-
  Prepare a repository for Terraform execution: configure Git for private modules,
  install Terraform, run fmt/validate, and invoke tfsec (always on).
author: Tesco Terraform Tooling Team
inputs:
  terraform_version:
    description: Terraform CLI version to install.
    required: false
    default: "1.8.5"
runs:
  using: composite
  steps:
    - name: Configure Git for private modules
      shell: bash
      env:
        GITHUB_TOKEN: ${{ github.token }}
      run: |
        set -euo pipefail
        if [ -n "${GITHUB_TOKEN:-}" ]; then
          git config --global url."https://x-access-token:${GITHUB_TOKEN}@github.com/".insteadOf "https://github.com/"
        fi

    - name: Set up Terraform
      uses: hashicorp/setup-terraform@v3
      with:
        terraform_version: ${{ inputs.terraform_version }}

    - name: Terraform fmt check
      shell: bash
      run: terraform fmt -check -diff

    - name: Terraform init (local)
      shell: bash
      run: terraform init -backend=false -input=false

    - name: Terraform validate
      shell: bash
      run: terraform validate -no-color

    - name: Run tfsec
      uses: aquasecurity/tfsec-pr-commenter-action@v1.3.1
      with:
        tfsec_args: --soft-fail --minimum-severity high
        github_token: ${{ github.token }}
