name: Terraform Setup
description: >-
  Prepare a repository for Terraform execution: configure Git for private modules,
  install Terraform, run fmt/validate, and invoke tfsec (always on).
author: Tesco Terraform Tooling Team
inputs:
  terraform_version:
    description: Terraform CLI version to install.
    required: false
    default: "1.8.5"
  environment:
    description: Environment name (used to select backend config file at env/<env>/<env>.tfbackend)
    required: true
runs:
  using: composite
  steps:
    - name: Configure Git for private modules
      shell: bash
      env:
        GITHUB_TOKEN: ${{ github.token }}
      run: |
        set -euo pipefail
        if [ -n "${GITHUB_TOKEN:-}" ]; then
          git config --global url."https://x-access-token:${GITHUB_TOKEN}@github.com/".insteadOf "https://github.com/"
        fi

    - name: Render backend config (optional)
      shell: bash
      env:
        ENV_NAME: ${{ inputs.environment }}
        REPO_NAME: ${{ github.repository }}
      run: |
        set -euo pipefail
        TEMPLATE_PATH="backend-config.template"
        if [ -f "$TEMPLATE_PATH" ]; then
          OUT_DIR="env/${ENV_NAME}"
          mkdir -p "$OUT_DIR"
          OUT_FILE="${OUT_DIR}/${ENV_NAME}.tfbackend"
          REPO_BASENAME="${REPO_NAME##*/}"
          export ENV="$ENV_NAME"
          export REPO="$REPO_BASENAME"
          export BUCKET="ims-terraform-infrastructure-state-${ENV_NAME}"
          export LOCK_TABLE="ims-terraform-infrastructure-state-lock-${ENV_NAME}"
          export REGION="eu-west-1"
          export KEY="ims-${REPO_BASENAME}-${ENV_NAME}.tfstate"
          if command -v envsubst >/dev/null 2>&1; then
            envsubst < "$TEMPLATE_PATH" > "$OUT_FILE"
          else
            printf '%s\n' \
              "bucket         = \"$BUCKET\"" \
              "key            = \"$KEY\"" \
              "region         = \"$REGION\"" \
              "dynamodb_table = \"$LOCK_TABLE\"" \
              > "$OUT_FILE"
          fi
          echo "Rendered backend to $OUT_FILE"
        fi

    - name: Set up Terraform
      uses: hashicorp/setup-terraform@v3
      with:
        terraform_version: ${{ inputs.terraform_version }}

    - name: Terraform fmt check
      shell: bash
      run: terraform fmt -check -diff

    - name: Terraform init (backend)
      shell: bash
      run: terraform init -input=false -reconfigure -backend-config="env/${{ inputs.environment }}/${{ inputs.environment }}.tfbackend"

    - name: Terraform validate
      shell: bash
      run: terraform validate -no-color

    - name: Run tfsec
      uses: aquasecurity/tfsec-pr-commenter-action@v1.3.1
      with:
        tfsec_args: --soft-fail --minimum-severity high
        github_token: ${{ github.token }}
