name: Terratest

on:
  workflow_call:
    inputs:
      go_version:
        description: Go toolchain version for Terratest.
        required: false
        type: string
        default: "1.23.6"
      working_directory:
        description: Directory containing Terratest sources.
        required: false
        type: string
        default: "test"
      test_pattern:
        description: Test name regex or 'all'.
        required: false
        type: string
        default: "all"
      timeout:
        description: Go test timeout value.
        required: false
        type: string
        default: "20m"
      environment:
        description: Environment name used to resolve AWS account and role.
        required: false
        type: string
        default: "sandbox"
  workflow_dispatch:
    inputs:
      go_version:
        description: Go toolchain version for Terratest.
        required: false
        default: "1.23.6"
      working_directory:
        description: Directory containing Terratest sources.
        required: false
        default: "test"
      test_pattern:
        description: Test name regex or 'all'.
        required: false
        default: "all"
      timeout:
        description: Go test timeout value.
        required: false
        default: "20m"
      environment:
        description: Environment name used to resolve AWS account and role.
        required: false
        default: "sandbox"

permissions:
  contents: read
  id-token: write
  pull-requests: write

concurrency:
  group: terratest-${{ github.ref }}
  cancel-in-progress: false

jobs:
  # Single job with environment-scoped AWS account var
  terratest:
    name: Run Terratest
    runs-on: ubuntu-latest
    environment: ${{ inputs.environment }}
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Summarise inputs and trigger context
        uses: granthouston44/terraform-actions/.github/actions/print-run-context@v0.2.1
        with:
          title: Terratest Workflow Context
          environment: ${{ inputs.environment }}
          aws_account_id: ${{ vars.AWS_ACCOUNT_ID }}
          aws_role_arn: arn:aws:iam::${{ vars.AWS_ACCOUNT_ID }}:role/ims-terraform-infrastructure-role-${{ inputs.environment }}
          go_version: ${{ inputs.go_version }}
          terratest_working_directory: ${{ inputs.working_directory }}
          terratest_pattern: ${{ inputs.test_pattern }}
          terratest_timeout: ${{ inputs.timeout }}
          application: ${{ inputs.working_directory }}
          action_type: test
          region: eu-west-1

      - name: Run Terratest (composite)
        uses: granthouston44/terraform-actions/.github/actions/run-terratest@v0.2.2
        with:
          go_version: ${{ inputs.go_version }}
          working_directory: ${{ inputs.working_directory }}
          test_pattern: ${{ inputs.test_pattern }}
          timeout: ${{ inputs.timeout }}
          aws_role_to_assume: arn:aws:iam::${{ vars.AWS_ACCOUNT_ID }}:role/ims-terraform-infrastructure-role-${{ inputs.environment }}
          aws_region: eu-west-1
          aws_session_name: github-actions
          formatter: gotestsum
