name: Terraform Module

on:
  workflow_call:
    inputs:
      working_directory:
        description: Path to the Terraform module root.
        required: true
        type: string
      environment:
        description: Environment name used for backend/vars, approvals and role resolution.
        required: true
        type: string
  workflow_dispatch:
    inputs:
      working_directory:
        description: Path to the Terraform module root.
        required: true
        default: "."
      environment:
        description: Environment name (drives backend/vars/plan/approval/role)
        required: true
        default: "prod"

permissions:
  contents: read
  id-token: write
  pull-requests: write

concurrency:
  group: terraform-${{ inputs.working_directory }}-${{ github.ref }}
  cancel-in-progress: false

jobs:
  context:
    name: Run Context
    runs-on: ubuntu-latest
    environment: ${{ inputs.environment }}
    outputs:
      effective_role_arn: ${{ steps.compute.outputs.effective_role_arn }}
    steps:
      - name: Compute effective role ARN
        id: compute
        shell: bash
        env:
          ENV: ${{ inputs.environment }}
          ROLE_BASE: ims-terraform-infrastructure-role
          ACCOUNT: ${{ vars.AWS_ACCOUNT_ID }}
        run: |
          set -euo pipefail
          ACCT="$ACCOUNT"
          ROLE_ARN=""
          if [ -n "${ACCT}" ]; then
            ROLE_ARN="arn:aws:iam::${ACCT}:role/${ROLE_BASE}-${ENV}"
          fi
          echo "account_id=${ACCT}" >> "$GITHUB_OUTPUT"
          echo "effective_role_arn=${ROLE_ARN}" >> "$GITHUB_OUTPUT"

      - name: Summarise inputs and trigger context
        uses: granthouston44/terraform-actions/.github/actions/print-run-context@v1
        with:
          title: Terraform Module Workflow Context
          environment: ${{ inputs.environment }}
          aws_account_id: ${{ steps.compute.outputs.account_id }}
          aws_role_arn: ${{ steps.compute.outputs.effective_role_arn }}
          working_directory: ${{ inputs.working_directory }}
          backend_config_file: computed (ims-terraform-infrastructure-state-<env>, ims-<repo>-<env>.tfstate)
          var_file: env/${{ inputs.environment }}/${{ inputs.environment }}.tfvars
          plan_file: plan-${{ inputs.environment }}.tfplan
          terraform_version: 1.8.5
          notes: "Reusable Terraform Module Workflow"
  plan:
    name: Plan
    runs-on: ubuntu-latest
    needs: context
    environment: ${{ inputs.environment }}
    defaults:
      run:
        working-directory: ${{ inputs.working_directory }}
    outputs:
      changed: ${{ steps.plan.outputs.plan_status == 'changes' }}
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Configure AWS credentials
        if: ${{ needs.context.outputs.effective_role_arn != '' }}
        uses: aws-actions/configure-aws-credentials@v4
        with:
          role-to-assume: ${{ needs.context.outputs.effective_role_arn }}
          aws-region: eu-west-1
          role-session-name: github-actions

      - name: Terraform setup
        uses: granthouston44/terraform-actions/.github/actions/terraform-setup@v1

      - name: Terraform plan
        id: plan
        uses: granthouston44/terraform-actions/.github/actions/terraform-plan@v1
        with:
          environment: ${{ inputs.environment }}
          aws_account_id: ${{ vars.AWS_ACCOUNT_ID }}
          var_file: env/${{ inputs.environment }}/${{ inputs.environment }}.tfvars

      # PR comment step removed per request

  plan-approval:
    name: Plan Approval Gate
    if: ${{ github.ref == 'refs/heads/main' && needs.plan.outputs.changed == 'true' }}
    runs-on: ubuntu-latest
    needs: [plan]
    environment: ${{ inputs.environment }}
    steps:
      - name: Await environment approval
        run: echo "Environment approval granted for plan in ${{ inputs.environment }}"

  apply:
    name: Apply
    if: ${{ github.ref == 'refs/heads/main' && needs.plan.outputs.changed == 'true' }}
    runs-on: ubuntu-latest
    needs: [plan, plan-approval]
    environment: ${{ inputs.environment }}
    defaults:
      run:
        working-directory: ${{ inputs.working_directory }}
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Configure AWS credentials
        if: ${{ needs.context.outputs.effective_role_arn != '' }}
        uses: aws-actions/configure-aws-credentials@v4
        with:
          role-to-assume: ${{ needs.context.outputs.effective_role_arn }}
          aws-region: eu-west-1
          role-session-name: github-actions

      - name: Terraform setup
        uses: granthouston44/terraform-actions/.github/actions/terraform-setup@v1

      - name: Terraform apply
        uses: granthouston44/terraform-actions/.github/actions/terraform-apply@v1
        with:
          environment: ${{ inputs.environment }}
          aws_account_id: ${{ vars.AWS_ACCOUNT_ID }}
