name: Terraform Module

on:
  workflow_call:
    inputs:
      working_directory:
        description: Path to the Terraform module root.
        required: true
        type: string
      backend_config_file:
        description: Optional backend config file for remote state.
        required: false
        type: string
        default: ""
      var_file:
        description: Optional tfvars file for plan/apply.
        required: false
        type: string
        default: ""
      plan_file:
        description: Plan file name to generate and reuse for apply.
        required: false
        type: string
        default: "terraform.tfplan"
      terraform_version:
        description: Terraform CLI version to install.
        required: false
        type: string
        default: "1.8.5"
      environment:
        description: Protected environment name used to gate apply.
        required: false
        type: string
        default: "prod"
      artifact_name:
        description: Artifact name for plan handoff between jobs.
        required: false
        type: string
        default: "tfplan"
      go_version:
        description: Go toolchain version for Terratest.
        required: false
        type: string
        default: "1.23.6"
      terratest_working_directory:
        description: Directory containing Terratest sources.
        required: false
        type: string
        default: "test"
      terratest_pattern:
        description: Test name regex or 'all'.
        required: false
        type: string
        default: "all"
      terratest_timeout:
        description: Go test timeout value.
        required: false
        type: string
        default: "20m"
      aws_role_to_assume:
        description: Optional IAM role ARN used by tests/plan/apply.
        required: false
        type: string
        default: ""
      aws_region:
        description: AWS region for assumed role and Terraform.
        required: false
        type: string
        default: "eu-west-1"
      aws_session_name:
        description: Session name for STS assume-role calls.
        required: false
        type: string
        default: "github-actions"
      aws_account_id:
        description: Optional AWS account ID. If provided and aws_role_to_assume is empty, a role ARN will be constructed.
        required: false
        type: string
        default: ""
      role_name:
        description: Base role name used when constructing the role ARN from aws_account_id; environment will be appended as a suffix.
        required: false
        type: string
        default: "ims-terraform-infrastructure-role"
      additional_init_args:
        description: Extra args appended to terraform init.
        required: false
        type: string
        default: ""
      additional_plan_args:
        description: Extra args appended to terraform plan.
        required: false
        type: string
        default: ""
      additional_apply_args:
        description: Extra args appended to terraform apply.
        required: false
        type: string
        default: ""
      enable_terratest:
        description: Run the Terratest job as part of this workflow.
        required: false
        type: boolean
        default: true

permissions:
  contents: read
  id-token: write
  pull-requests: write

concurrency:
  group: terraform-${{ inputs.working_directory }}-${{ github.ref }}
  cancel-in-progress: false

jobs:
  context:
    name: Run Context
    runs-on: ubuntu-latest
    outputs:
      effective_role_arn: ${{ steps.compute.outputs.effective_role_arn }}
    steps:
      - name: Compute effective role ARN
        id: compute
        shell: bash
        env:
          IN_ROLE_ARN: ${{ inputs.aws_role_to_assume }}
          IN_ACCOUNT: ${{ inputs.aws_account_id }}
          ROLE_BASE: ${{ inputs.role_name }}
          ENV: ${{ inputs.environment }}
        run: |
          set -euo pipefail
          ROLE_ARN="$IN_ROLE_ARN"
          if [ -z "$ROLE_ARN" ] && [ -n "$IN_ACCOUNT" ]; then
            BASE_NAME="${ROLE_BASE:-ims-terraform-infrastructure-role}"
            ROLE_NAME="${BASE_NAME}-${ENV}"
            ROLE_ARN="arn:aws:iam::${IN_ACCOUNT}:role/${ROLE_NAME}"
          fi
          echo "effective_role_arn=$ROLE_ARN" >> "$GITHUB_OUTPUT"

      - name: Summarise inputs and trigger context
        shell: bash
        env:
          ENVIRONMENT: ${{ inputs.environment }}
          WORKDIR: ${{ inputs.working_directory }}
          BACKEND: ${{ inputs.backend_config_file }}
          VAR_FILE: ${{ inputs.var_file }}
          PLAN_FILE: ${{ inputs.plan_file }}
          GO_VERSION: ${{ inputs.go_version }}
          TEST_DIR: ${{ inputs.terratest_working_directory }}
          TEST_PATTERN: ${{ inputs.terratest_pattern }}
          TEST_TIMEOUT: ${{ inputs.terratest_timeout }}
          AWS_ROLE_ARN: ${{ steps.compute.outputs.effective_role_arn }}
          AWS_ACCOUNT_ID: ${{ inputs.aws_account_id }}
        run: |
          {
            echo "## Terraform Module Workflow Context"
            echo "- Trigger: ${{ github.event_name }}"
            echo "- Actor: ${{ github.actor }} (triggering: ${{ github.triggering_actor }})"
            echo "- Ref: ${{ github.ref }}"
            echo "- Workflow: ${{ github.workflow }} (#${{ github.run_number }}, id ${{ github.run_id }})"
            echo "- Environment: ${ENVIRONMENT}"
            echo "- Working directory: ${WORKDIR}"
            echo "- Backend config file: ${BACKEND}"
            echo "- Var file: ${VAR_FILE}"
            echo "- Plan file: ${PLAN_FILE}"
            echo "- Terratest: go ${GO_VERSION}, dir ${TEST_DIR}, pattern ${TEST_PATTERN}, timeout ${TEST_TIMEOUT}"
            echo "- AWS account id: ${AWS_ACCOUNT_ID}"
            echo "- AWS role ARN: ${AWS_ROLE_ARN}"
          } >> "$GITHUB_STEP_SUMMARY"
  terratest:
    name: Terratest
    runs-on: ubuntu-latest
    if: ${{ inputs.enable_terratest }}
    needs: context
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Run Terratest
        if: ${{ needs.context.outputs.effective_role_arn != '' }}
        uses: ./.github/actions/run-terratest
        with:
          go_version: ${{ inputs.go_version }}
          working_directory: ${{ inputs.terratest_working_directory }}
          test_pattern: ${{ inputs.terratest_pattern }}
          timeout: ${{ inputs.terratest_timeout }}
          aws_role_to_assume: ${{ needs.context.outputs.effective_role_arn }}
          aws_region: ${{ inputs.aws_region }}
          aws_session_name: ${{ inputs.aws_session_name }}

  plan:
    name: Plan
    runs-on: ubuntu-latest
    needs: context
    outputs:
      changed: ${{ steps.plan.outputs.plan_status == 'changes' }}
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Terraform setup (fmt/validate/tfsec)
        uses: ./.github/actions/terraform-setup
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          terraform_version: ${{ inputs.terraform_version }}
          working_directory: ${{ inputs.working_directory }}
          run_local_init: false

      - name: Terraform plan
        id: plan
        uses: ./.github/actions/terraform-plan
        with:
          working_directory: ${{ inputs.working_directory }}
          backend_config_file: ${{ inputs.backend_config_file }}
          var_file: ${{ inputs.var_file }}
          plan_file: ${{ inputs.plan_file }}
          additional_init_args: ${{ inputs.additional_init_args }}
          additional_plan_args: ${{ inputs.additional_plan_args }}
          aws_role_to_assume: ${{ needs.context.outputs.effective_role_arn }}
          aws_region: ${{ inputs.aws_region }}
          aws_session_name: ${{ inputs.aws_session_name }}
          artifact_name: ${{ inputs.artifact_name }}

      - name: PR comment with plan
        if: ${{ github.event_name == 'pull_request' }}
        uses: marocchino/sticky-pull-request-comment@v2
        with:
          recreate: true
          path: ${{ steps.plan.outputs.plan_text_path }}

  plan-approval:
    name: Plan Approval Gate
    if: ${{ github.ref == 'refs/heads/main' && needs.plan.outputs.changed == 'true' }}
    runs-on: ubuntu-latest
    needs: [plan]
    environment: ${{ inputs.environment }}
    steps:
      - name: Await environment approval
        run: echo "Environment approval granted for plan in ${{ inputs.environment }}"

  apply:
    name: Apply
    if: ${{ github.ref == 'refs/heads/main' && needs.plan.outputs.changed == 'true' }}
    runs-on: ubuntu-latest
    needs: [plan, plan-approval]
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Terraform setup (fmt/validate)
        uses: ./.github/actions/terraform-setup
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          terraform_version: ${{ inputs.terraform_version }}
          working_directory: ${{ inputs.working_directory }}
          run_local_init: false

      - name: Terraform apply
        uses: ./.github/actions/terraform-apply
        with:
          working_directory: ${{ inputs.working_directory }}
          backend_config_file: ${{ inputs.backend_config_file }}
          var_file: ${{ inputs.var_file }}
          plan_file: ${{ inputs.plan_file }}
          additional_init_args: ${{ inputs.additional_init_args }}
          additional_apply_args: ${{ inputs.additional_apply_args }}
          apply_auto_approve: false
          aws_role_to_assume: ${{ needs.context.outputs.effective_role_arn }}
          aws_region: ${{ inputs.aws_region }}
          aws_session_name: ${{ inputs.aws_session_name }}
          artifact_name: ${{ inputs.artifact_name }}
